name: ahbabmembers
description: App for Members of Al-Ahbab Society, Doha, Qatar

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Firebase
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5

  #Shared Preferences
  shared_preferences: ^2.0.11

  #Cryptography
  crypto: ^3.0.1

  #Some Useful Regular Expression
  regexpattern: ^2.0.1

  #Icons
  flutter_vector_icons: ^1.0.0

  #getwidget
  getwidget: ^2.0.4

  internet_connection_checker: ^0.0.1+3

  stream_transform: ^2.0.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.3.3
  firebase_analytics: ^9.0.0
  month_picker_dialog: ^0.4.0
  provider: ^6.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #Launcher Icons
  flutter_launcher_icons: "^0.9.2"

  #Splash Screen






# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi.ttf
        - asset: assets/fonts/SolaimanLipiBold.ttf
          weight: 900

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
